variable "oauth_config_url" {}
variable "google_client_id" {}
variable "google_client_secret" {}
variable "server_salt" {}
variable "ui_url" {}
variable "aws_access_key_id" {}
variable "aws_secret_access_key" {}
variable "region" {}
variable "bucket_name" {}
variable "memory_db_url" {}
variable "env" {}
